# @path: derivations/zcode/sources.nix
# @author: redskaber
# @datetime: 2026-08-04
# @description: Pinned download metadata for ZCode (auto-generated by update.sh).
#
# All four platforms are pinned with URLs + nix32 sha256 hashes. Hashes were
# computed on 2026-08-04 by:
#   1. Downloading each artifact from cdn-zcode.z.ai
#   2. sha256sum -> hex digest
#   3. `nix hash convert --hash-algo sha256 --to nix32 <hex>` (or nix-prefetch-url)
# Verified against the Trae pipeline (same hash pipeline; cross-checked with
# the Trae arm64 deb whose nix32 hash is publicly known).
#
# Hex digests for audit:
#   x86_64-linux  : e49803cd8c46cdc0b2ed61e27addfd1fa7cc172ff1ee1b7aeb2a8eb5d8453204
#   aarch64-linux : 5a0a6fc9e81e4494cb744a0b3ca4bf9957ba94d8fb814a74ddef6188bf8a2ad0
#   x86_64-darwin : 8f496426828411940a03e757f9a9f56ee684f9b59274351f7f7b96e4c55c4df8
#   aarch64-darwin: e4f93eb3fa51825fc3a443b3307dc52eda98c018d9ac326a22d254f8aa77ac8b

{
  version = "3.6.5";

  x86_64-linux = {
    url = "https://cdn-zcode.z.ai/zcode/electron/releases/3.6.5/linux-x64/ZCode-3.6.5-linux-x64.deb";
    sha256 = "011j8pcbb3iaxdx1pvpi5wbwr9qzzpfpmqk1xnrc1ka6ik6h7674";
  };

  aarch64-linux = {
    url = "https://cdn-zcode.z.ai/zcode/electron/releases/3.6.5/linux-arm64/ZCode-3.6.5-linux-arm64.deb";
    sha256 = "1l1aiazqhqggvms4m0gvv2ablmwrpyj3q2safk5r8i0yx34ny2js";
  };

  x86_64-darwin = {
    url = "https://cdn-zcode.z.ai/zcode/electron/releases/3.6.5/macos-x64/ZCode-3.6.5-mac-x64.dmg";
    sha256 = "1y2dbk2y95kvgwgkax4jnpwq9rkfynlzjmz70c5984c4h8k68jcg";
  };

  aarch64-darwin = {
    url = "https://cdn-zcode.z.ai/zcode/electron/releases/3.6.5/macos-arm64/ZCode-3.6.5-mac-arm64.dmg";
    sha256 = "12xcfymghm6j49m35b6r3309inifqmyk1cs3lk1mz0jizarkxyg4";
  };
}
